# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDCd4umn7HuXi7a5v_1dAE3FdFJTF4Y2
"""

a=4
b=5
c=a+b
print("Addition",c)

